name: Download zips
description: download zip from github repository packages uploaded through maven

inputs:
  artifact-id:
    description: 'Maven dependency artifact id.'
    required: true

runs:
  steps:
    - name: Download source zips
      run: |
        echo ${{ inputs.artifact-id }} 
      shell: bash
