name: Download zips
description: download zip from github repository packages uploaded through maven

inputs:
  org_name:
    description: 'Org name of the repo'
    required: true


runs:
  using: "composite"
  steps:
    - name: Download source zips
      run: |
        echo "${{inputs.org_name}}"
      shell: bash
